### PR TITLE
Update Mine.html

### PR DESCRIPTION
**Pull request by aa123bb**

### CODE REVIEW

**Comment by aa123bb** [comment]
please can you help me approve the changes which I made in my mine.html. Thank you.

**Comment by sn3ll** [comment]
You can run these changes locally and do not need to be merged. Thanks :)

**Comment by aa123bb** [comment]
Please how can I run it locally?

**Comment by sn3ll** [comment]
Download the mine.html file and open it in a web browser. That will run it locally on your machine.

**Comment by aa123bb** [comment]
Ok thank you.

**Pull request closed without merging**
